# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckapp', '0005_auto_20160324_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upvotes',
            field=models.ManyToManyField(to='duckapp.Answer'),
        ),
    ]
