# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckapp', '0006_userprofile_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvote', to='duckapp.Answer'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvote', to='duckapp.Answer'),
        ),
    ]
